export const MONITORING_STAGES_REGISTRY = {
    2: {
        label: 'Monitoring 2',
        stageNumber: 2,
        key: 'monitoring2_no',
        api: {
            list: 'monitorings-v3/list',
            detail: 'monitorings-v3/detail',
            verifFC: 'monitorings-v3/verification-fc',
            verifUM: 'monitorings-v3/verification-um',
            unverif: 'monitorings-v3/unverification',
            delete: 'monitorings-v3/delete',
            export: 'monitorings-v3/export',
        },
        deletePayloadKeys: ['monitoring2_no'],
        features: {
            hasExportSummary: true,
            hasGeneratePopulate: true,
            hasPrintLabel: true,
        },
        populate: {
            targetStage: 3,
            endpoint: 'populate-monitorings-v3/create',
        },
        treeDetailHeaders: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Nomor Pohon', value: 'tree_no' },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Umur Pohon', value: 'tree_age' },
            { text: 'Kondisi Sekitar', value: 'tree_condition' },
            { text: 'Tinggi (cm)', value: 'height' },
            { text: 'Diameter (cm)', value: 'diameter' },
            { text: 'Status Hidup', value: 'life_status' },
            { text: 'Pupuk', value: 'pest' },
            { text: 'Deskripsi Pupuk', value: 'pest_description' },
        ],
        monitoringTreeDetail: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Kategori Pohon', value: 'tree_category' },
            { text: 'Jumlah Hidup', value: 'life' },
        ],
    },
    3: {
        label: 'Monitoring 3',
        stageNumber: 3,
        key: 'monitoring3_no',
        api: {
            list: 'monitorings-v3/list',
            detail: 'monitorings-v3/detail',
            verifFC: 'monitorings-v3/verification-fc',
            verifUM: 'monitorings-v3/verification-um',
            unverif: 'monitorings-v3/unverification',
            delete: 'monitorings-v3/delete',
            export: 'monitorings-v3/export',
        },
        deletePayloadKeys: ['monitoring3_no'],
        features: {
            hasExportSummary: true,
            hasGeneratePopulate: true,
            hasPrintLabel: true,
        },
        populate: {
            targetStage: 4,
            endpoint: 'populate-monitorings-v3/create',
        },
        treeDetailHeaders: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Nomor Pohon', value: 'tree_no' },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Umur Pohon', value: 'tree_age' },
            { text: 'Kondisi Sekitar', value: 'tree_condition' },
            { text: 'Tinggi (cm)', value: 'height' },
            { text: 'Diameter (cm)', value: 'diameter' },
            { text: 'Status Hidup', value: 'life_status' },
            { text: 'Pupuk', value: 'pest' },
            { text: 'Deskripsi Pupuk', value: 'pest_description' },
        ],
        monitoringTreeDetail: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Kategori Pohon', value: 'tree_category' },
            { text: 'Jumlah Hidup', value: 'life' },
        ],
    },
    4: {
        label: 'Monitoring 4',
        stageNumber: 4,
        key: 'monitoring4_no',
        api: {
            list: 'monitorings-v3/list',
            detail: 'monitorings-v3/detail',
            verifFC: 'monitorings-v3/verification-fc',
            verifUM: 'monitorings-v3/verification-um',
            unverif: 'monitorings-v3/unverification',
            delete: 'monitorings-v3/delete',
            export: 'monitorings-v3/export',
        },
        deletePayloadKeys: ['monitoring4_no'],
        features: {
            hasExportSummary: true,
            hasGeneratePopulate: true,
            hasPrintLabel: true,
        },
        populate: {
            targetStage: 5,
            endpoint: 'populate-monitorings-v3/create',
        },
        treeDetailHeaders: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Nomor Pohon', value: 'tree_no' },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Umur Pohon', value: 'tree_age' },
            { text: 'Kondisi Sekitar', value: 'tree_condition' },
            { text: 'Tinggi (cm)', value: 'height' },
            { text: 'Diameter (cm)', value: 'diameter' },
            { text: 'Status Hidup', value: 'life_status' },
            { text: 'Pupuk', value: 'pest' },
            { text: 'Deskripsi Pupuk', value: 'pest_description' },
        ],
        monitoringTreeDetail: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Kategori Pohon', value: 'tree_category' },
            { text: 'Jumlah Hidup', value: 'life' },
        ],
    },
    5: {
        label: 'Monitoring 5',
        stageNumber: 5,
        key: 'monitoring5_no',
        api: {
            list: 'monitorings-v3/list',
            detail: 'monitorings-v3/detail',
            verifFC: 'monitorings-v3/verification-fc',
            verifUM: 'monitorings-v3/verification-um',
            unverif: 'monitorings-v3/unverification',
            delete: 'monitorings-v3/delete',
            export: 'monitorings-v3/export',
        },
        deletePayloadKeys: ['monitoring5_no'],
        features: {
            hasExportSummary: true,
            hasGeneratePopulate: false,
            hasPrintLabel: true,
        },
        populate: null,
        treeDetailHeaders: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Nomor Pohon', value: 'tree_no' },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Umur Pohon', value: 'tree_age' },
            { text: 'Kondisi Sekitar', value: 'tree_condition' },
            { text: 'Tinggi (cm)', value: 'height' },
            { text: 'Diameter (cm)', value: 'diameter' },
            { text: 'Status Hidup', value: 'life_status' },
            { text: 'Pupuk', value: 'pest' },
            { text: 'Deskripsi Pupuk', value: 'pest_description' },
        ],
        monitoringTreeDetail: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Kategori Pohon', value: 'tree_category' },
            { text: 'Jumlah Hidup', value: 'life' },
        ],
    },
}