export const MONITORING_STAGES_REGISTRY = {
    2: {
        label: 'Monitoring 2',
        stageNumber: 2,
        key: 'monitoring2_no',
        api: {
            list: 'monitorings-v3/list/web',
            detail: 'monitorings-v3/detail',
            verifFC: 'monitorings-v3/update/main',
            verifUM: 'monitorings-v3/update/main',
            unverif: 'monitorings-v3/update/main',
            delete: 'monitorings-v3/delete',
            export: 'monitorings-v3/export',
        },
        deletePayloadKeys: ['monitoring2_no'],
        features: {
            hasExportSummary: true,
            hasGeneratePopulate: true,
            hasPrintLabel: true,
        },
        populate: {
            targetStage: 3,
            endpoint: 'populate-monitorings-v3/create',
        },
        treeDetailHeaders: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Nomor Pohon', value: 'tree_no' },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Umur Pohon', value: 'tree_age' },
            { text: 'Kondisi Sekitar', value: 'tree_condition' },
            { text: 'Tinggi (cm)', value: 'height' },
            { text: 'Diameter (cm)', value: 'diameter' },
            { text: 'Status Hidup', value: 'life_status' },
            { text: 'Pupuk', value: 'pest' },
            { text: 'Deskripsi Pupuk', value: 'pest_description' },
        ],
        monitoringTreeDetail: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Kategori Pohon', value: 'tree_category' },
            { text: 'Jumlah Hidup', value: 'life' },
        ],
        pestDiseaseHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'pest_disease_type', width: '100px' },
            { text: 'Nama', value: 'pest_disease_name' },
            { text: 'Deskripsi', value: 'pest_disease_description' },
            { text: 'Est. Mati', value: 'plant_dead_estimation', width: '100px' },
            { text: 'Pohon Mati', value: 'tree_dead', width: '100px' },
        ],
        disasterHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'disaster_type', width: '150px' },
            { text: 'Nama', value: 'disaster_name' },
            { text: 'Tahun', value: 'disaster_year', width: '80px' },
            { text: 'Deskripsi', value: 'disaster_description' },
            { text: 'Dampak', value: 'disaster_impact' },
            { text: 'Est. Mati', value: 'plant_dead_estimation', width: '100px' },
        ],
        complainHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'complain_type', width: '150px' },
            { text: 'Keluhan', value: 'complain_name' },
            { text: 'Deskripsi', value: 'complain_description' },
        ],
        harvestHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Jenis Panen', value: 'harvest_type' },
            { text: 'Kode Pohon', value: 'tree_code', width: '120px' },
            { text: 'Intensitas', value: 'harvest_intensity', width: '150px' },
        ],
        plantCompanionHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'plant_type', width: '150px' },
            { text: 'Nama Tanaman', value: 'plant_name' },
        ],
    },
    3: {
        label: 'Monitoring 3',
        stageNumber: 3,
        key: 'monitoring3_no',
        api: {
            list: 'monitorings-v3/list/web',
            detail: 'monitorings-v3/detail',
            verifFC: 'monitorings-v3/update/main',
            verifUM: 'monitorings-v3/update/main',
            unverif: 'monitorings-v3/update/main',
            delete: 'monitorings-v3/delete',
            export: 'monitorings-v3/export',
        },
        deletePayloadKeys: ['monitoring3_no'],
        features: {
            hasExportSummary: true,
            hasGeneratePopulate: true,
            hasPrintLabel: true,
        },
        populate: {
            targetStage: 4,
            endpoint: 'populate-monitorings-v3/create',
        },
        treeDetailHeaders: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Nomor Pohon', value: 'tree_no' },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Umur Pohon', value: 'tree_age' },
            { text: 'Kondisi Sekitar', value: 'tree_condition' },
            { text: 'Tinggi (cm)', value: 'height' },
            { text: 'Diameter (cm)', value: 'diameter' },
            { text: 'Status Hidup', value: 'life_status' },
            { text: 'Pupuk', value: 'pest' },
            { text: 'Deskripsi Pupuk', value: 'pest_description' },
        ],
        monitoringTreeDetail: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Kategori Pohon', value: 'tree_category' },
            { text: 'Jumlah Hidup', value: 'life' },
        ],
        pestDiseaseHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'pest_disease_type', width: '100px' },
            { text: 'Nama', value: 'pest_disease_name' },
            { text: 'Deskripsi', value: 'pest_disease_description' },
            { text: 'Est. Mati', value: 'plant_dead_estimation', width: '100px' },
            { text: 'Pohon Mati', value: 'tree_dead', width: '100px' },
        ],
        disasterHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'disaster_type', width: '150px' },
            { text: 'Nama', value: 'disaster_name' },
            { text: 'Tahun', value: 'disaster_year', width: '80px' },
            { text: 'Deskripsi', value: 'disaster_description' },
            { text: 'Dampak', value: 'disaster_impact' },
            { text: 'Est. Mati', value: 'plant_dead_estimation', width: '100px' },
        ],
        complainHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'complain_type', width: '150px' },
            { text: 'Keluhan', value: 'complain_name' },
            { text: 'Deskripsi', value: 'complain_description' },
        ],
        harvestHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Jenis Panen', value: 'harvest_type' },
            { text: 'Kode Pohon', value: 'tree_code', width: '120px' },
            { text: 'Intensitas', value: 'harvest_intensity', width: '150px' },
        ],
        plantCompanionHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'plant_type', width: '150px' },
            { text: 'Nama Tanaman', value: 'plant_name' },
        ],
    },
    4: {
        label: 'Monitoring 4',
        stageNumber: 4,
        key: 'monitoring4_no',
        api: {
            list: 'monitorings-v3/list/web',
            detail: 'monitorings-v3/detail',
            verifFC: 'monitorings-v3/update/main',
            verifUM: 'monitorings-v3/update/main',
            unverif: 'monitorings-v3/update/main',
            delete: 'monitorings-v3/delete',
            export: 'monitorings-v3/export',
        },
        deletePayloadKeys: ['monitoring4_no'],
        features: {
            hasExportSummary: true,
            hasGeneratePopulate: true,
            hasPrintLabel: true,
        },
        populate: {
            targetStage: 5,
            endpoint: 'populate-monitorings-v3/create',
        },
        treeDetailHeaders: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Nomor Pohon', value: 'tree_no' },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Umur Pohon', value: 'tree_age' },
            { text: 'Kondisi Sekitar', value: 'tree_condition' },
            { text: 'Tinggi (cm)', value: 'height' },
            { text: 'Diameter (cm)', value: 'diameter' },
            { text: 'Status Hidup', value: 'life_status' },
            { text: 'Pupuk', value: 'pest' },
            { text: 'Deskripsi Pupuk', value: 'pest_description' },
        ],
        monitoringTreeDetail: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Kategori Pohon', value: 'tree_category' },
            { text: 'Jumlah Hidup', value: 'life' },
        ],
        pestDiseaseHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'pest_disease_type', width: '100px' },
            { text: 'Nama', value: 'pest_disease_name' },
            { text: 'Deskripsi', value: 'pest_disease_description' },
            { text: 'Est. Mati', value: 'plant_dead_estimation', width: '100px' },
            { text: 'Pohon Mati', value: 'tree_dead', width: '100px' },
        ],
        disasterHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'disaster_type', width: '150px' },
            { text: 'Nama', value: 'disaster_name' },
            { text: 'Tahun', value: 'disaster_year', width: '80px' },
            { text: 'Deskripsi', value: 'disaster_description' },
            { text: 'Dampak', value: 'disaster_impact' },
            { text: 'Est. Mati', value: 'plant_dead_estimation', width: '100px' },
        ],
        complainHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'complain_type', width: '150px' },
            { text: 'Keluhan', value: 'complain_name' },
            { text: 'Deskripsi', value: 'complain_description' },
        ],
        harvestHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Jenis Panen', value: 'harvest_type' },
            { text: 'Kode Pohon', value: 'tree_code', width: '120px' },
            { text: 'Intensitas', value: 'harvest_intensity', width: '150px' },
        ],
        plantCompanionHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'plant_type', width: '150px' },
            { text: 'Nama Tanaman', value: 'plant_name' },
        ],
    },
    5: {
        label: 'Monitoring 5',
        stageNumber: 5,
        key: 'monitoring5_no',
        api: {
            list: 'monitorings-v3/list/web',
            detail: 'monitorings-v3/detail',
            verifFC: 'monitorings-v3/update/main',
            verifUM: 'monitorings-v3/update/main',
            unverif: 'monitorings-v3/update/main',
            delete: 'monitorings-v3/delete',
            export: 'monitorings-v3/export',
        },
        deletePayloadKeys: ['monitoring5_no'],
        features: {
            hasExportSummary: true,
            hasGeneratePopulate: false,
            hasPrintLabel: true,
        },
        populate: null,
        treeDetailHeaders: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Nomor Pohon', value: 'tree_no' },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Umur Pohon', value: 'tree_age' },
            { text: 'Kondisi Sekitar', value: 'tree_condition' },
            { text: 'Tinggi (cm)', value: 'height' },
            { text: 'Diameter (cm)', value: 'diameter' },
            { text: 'Status Hidup', value: 'life_status' },
            { text: 'Pupuk', value: 'pest' },
            { text: 'Deskripsi Pupuk', value: 'pest_description' },
        ],
        monitoringTreeDetail: [
            { text: 'No', value: 'index', sortable: false },
            { text: 'Kode Pohon', value: 'tree_code' },
            { text: 'Nama Pohon', value: 'tree_name' },
            { text: 'Kategori Pohon', value: 'tree_category' },
            { text: 'Jumlah Hidup', value: 'life' },
        ],
        pestDiseaseHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'pest_disease_type', width: '100px' },
            { text: 'Nama', value: 'pest_disease_name' },
            { text: 'Deskripsi', value: 'pest_disease_description' },
            { text: 'Est. Mati', value: 'plant_dead_estimation', width: '100px' },
            { text: 'Pohon Mati', value: 'tree_dead', width: '100px' },
        ],
        disasterHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'disaster_type', width: '150px' },
            { text: 'Nama', value: 'disaster_name' },
            { text: 'Tahun', value: 'disaster_year', width: '80px' },
            { text: 'Deskripsi', value: 'disaster_description' },
            { text: 'Dampak', value: 'disaster_impact' },
            { text: 'Est. Mati', value: 'plant_dead_estimation', width: '100px' },
        ],
        complainHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'complain_type', width: '150px' },
            { text: 'Keluhan', value: 'complain_name' },
            { text: 'Deskripsi', value: 'complain_description' },
        ],
        harvestHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Jenis Panen', value: 'harvest_type' },
            { text: 'Kode Pohon', value: 'tree_code', width: '120px' },
            { text: 'Intensitas', value: 'harvest_intensity', width: '150px' },
        ],
        plantCompanionHeaders: [
            { text: 'No', value: 'index', sortable: false, width: '50px' },
            { text: 'Tipe', value: 'plant_type', width: '150px' },
            { text: 'Nama Tanaman', value: 'plant_name' },
        ],
    },
}