import moment from "moment/moment";
import Vue from "vue";
import Vuex from "vuex";
import { version, version_date_time } from "../../package.json";
import JustLoadingLineModul from "./scpecialEmails/JustLoadingLineModul";
import {
  Cirasea,
  Ciminyak,
  Soreang,
  Kebumen,
  Pati,
} from "./scpecialEmails/nurseryTeam";
import TaskForceEmail from "./scpecialEmails/taskForceTeam";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    apiConfig: {
      headers: {
        Authorization: `Bearer ${localStorage.getItem("token")}`,
      },
    },
    tmpProjectPurpose: localStorage.getItem("tmpProjectPurpose"),
    apiUrl: localStorage.getItem("BaseUrlGet"),
    apiUrlImage: localStorage.getItem("BaseUrl"),
    tmpProgramYear: localStorage.getItem("tmpProgramYear"),
    lightbox: {
      imgs: "",
      index: 0,
      show: false,
    },
    loadingOverlay: false,
    loadingOverlayText: null,
    permission: [
      "user-create",
      "user-detail",
      "user-update",
      "user-delete",
      "user-lookup",
      "user-list",
      "employee-create",
      "employee-detail",
      "employee-update",
      "employee-delete",
      "employee-lookup",
      "employee-list",
      "field-coordinator-create",
      "field-coordinator-detail",
      "field-coordinator-update",
      "field-coordinator-delete",
      "field-coordinator-lookup",
      "field-coordinator-list",
      "field-facilitator-create",
      "field-facilitator-detail",
      "field-facilitator-update",
      "field-facilitator-delete",
      "field-facilitator-lookup",
      "field-facilitator-list",
      "employee-menu-create",
      "employee-menu-detail",
      "employee-menu-update",
      "employee-menu-delete",
      "employee-menu-lookup",
      "employee-menu-list",
      "employee-manager-create",
      "employee-manager-detail",
      "employee-manager-update",
      "employee-manager-delete",
      "employee-manager-lookup",
      "employee-manager-list",
      "employee-position-create",
      "employee-position-detail",
      "employee-position-update",
      "employee-position-delete",
      "employee-position-lookup",
      "employee-position-list",
      "farmer-create",
      "farmer-detail",
      "farmer-update",
      "farmer-delete",
      "farmer-lookup",
      "farmer-list",
      "lahan-create",
      "lahan-detail",
      "lahan-update",
      "lahan-delete",
      "lahan-lookup",
      "lahan-list",
      "lahan-umum-create",
      "lahan-umum-detail",
      "lahan-umum-update",
      "lahan-umum-delete",
      "lahan-umum-lookup",
      "lahan-umum-list",
      "donor-create",
      "donor-detail",
      "donor-update",
      "donor-delete",
      "donor-lookup",
      "donor-list",
      "project-create",
      "project-detail",
      "project-update",
      "project-delete",
      "project-lookup",
      "project-list",
      "truck-driver-create",
      "truck-driver-detail",
      "truck-driver-update",
      "truck-driver-delete",
      "truck-driver-lookup",
      "truck-driver-list",
      "progression-create",
      "progression-detail",
      "progression-update",
      "progression-delete",
      "progression-lookup",
      "progression-list",
      "scooping-visit-create",
      "scooping-visit-detail",
      "scooping-visit-update",
      "scooping-visit-delete",
      "scooping-visit-lookup",
      "scooping-visit-list",
      "rra-pra-create",
      "rra-pra-detail",
      "rra-pra-update",
      "rra-pra-delete",
      "rra-pra-lookup",
      "rra-pra-list",
      "sosialisasi-program-create",
      "sosialisasi-program-detail",
      "sosialisasi-program-update",
      "sosialisasi-program-delete",
      "sosialisasi-program-lookup",
      "sosialisasi-program-list",
      "sosialisasi-tanam-create",
      "sosialisasi-tanam-detail",
      "sosialisasi-tanam-update",
      "sosialisasi-tanam-delete",
      "sosialisasi-tanam-lookup",
      "sosialisasi-tanam-list",
      "pelatihan-petani-create",
      "pelatihan-petani-detail",
      "pelatihan-petani-update",
      "pelatihan-petani-delete",
      "pelatihan-petani-lookup",
      "pelatihan-petani-list",
      "lubang-tanam-create",
      "lubang-tanam-detail",
      "lubang-tanam-update",
      "lubang-tanam-delete",
      "lubang-tanam-lookup",
      "lubang-tanam-list",
      "material-organic-create",
      "material-organic-detail",
      "material-organic-update",
      "material-organic-delete",
      "material-organic-lookup",
      "material-organic-list",
      "distribusi-create",
      "distribusi-detail",
      "distribusi-update",
      "distribusi-delete",
      "distribusi-lookup",
      "distribusi-list",
      "realisasi-tanam-create",
      "realisasi-tanam-detail",
      "realisasi-tanam-update",
      "realisasi-tanam-delete",
      "realisasi-tanam-lookup",
      "realisasi-tanam-list",
      "monitoring-create",
      "monitoring-detail",
      "monitoring-update",
      "monitoring-delete",
      "monitoring-lookup",
      "monitoring-list",
      "scooping-visit-v2-create",
      "scooping-visit-v2-detail",
      "scooping-visit-v2-update",
      "scooping-visit-v2-delete",
      "scooping-visit-v2-lookup",
      "scooping-visit-v2-list",
      "rra-pra-v2-create",
      "rra-pra-v2-detail",
      "rra-pra-v2-update",
      "rra-pra-v2-delete",
      "rra-pra-v2-lookup",
      "rra-pra-v2-list",
      "provinsi-create",
      "provinsi-detail",
      "provinsi-update",
      "provinsi-delete",
      "provinsi-lookup",
      "provinsi-list",
      "kabupaten-create",
      "kabupaten-detail",
      "kabupaten-update",
      "kabupaten-delete",
      "kabupaten-lookup",
      "kabupaten-list",
      "kecamatan-create",
      "kecamatan-detail",
      "kecamatan-update",
      "kecamatan-delete",
      "kecamatan-lookup",
      "kecamatan-list",
      "desa-create",
      "desa-detail",
      "desa-update",
      "desa-delete",
      "desa-lookup",
      "desa-list",
      "management-unit-create",
      "management-unit-detail",
      "management-unit-update",
      "management-unit-delete",
      "management-unit-lookup",
      "management-unit-list",
      "target-area-create",
      "target-area-detail",
      "target-area-update",
      "target-area-delete",
      "target-area-lookup",
      "target-area-list",
      "pekerjaan-create",
      "pekerjaan-detail",
      "pekerjaan-update",
      "pekerjaan-delete",
      "pekerjaan-lookup",
      "pekerjaan-list",
      "suku-create",
      "suku-detail",
      "suku-update",
      "suku-delete",
      "suku-lookup",
      "suku-list",
      "trees-create",
      "trees-detail",
      "trees-update",
      "trees-delete",
      "trees-lookup",
      "trees-list",
      "regional-create",
      "regional-detail",
      "regional-update",
      "regional-delete",
      "regional-lookup",
      "regional-list",
      "project-type-create",
      "project-type-detail",
      "project-type-update",
      "project-type-delete",
      "project-type-lookup",
      "project-type-list",
      "project-planting-purpose-create",
      "project-planting-purpose-detail",
      "project-planting-purpose-update",
      "project-planting-purpose-delete",
      "project-planting-purpose-lookup",
      "project-planting-purpose-list",
      "project-planting-environment-create",
      "project-planting-environment-detail",
      "project-planting-environment-update",
      "project-planting-environment-delete",
      "project-planting-environment-lookup",
      "project-planting-environment-list",
      "task-create",
      "task-detail",
      "task-update",
      "task-delete",
      "task-lookup",
      "task-list",
      "task-group-create",
      "task-group-detail",
      "task-group-update",
      "task-group-delete",
      "task-group-lookup",
      "task-group-list",
      "report-data-create",
      "report-data-detail",
      "report-data-update",
      "report-data-delete",
      "report-data-lookup",
      "report-data-list",
      "scooping-visit-verification-create",
      "scooping-visit-verification-detail",
      "scooping-visit-verification-update",
      "scooping-visit-verification-delete",
      "scooping-visit-verification-lookup",
      "scooping-visit-verification-list",
      "scooping-visit-unverification-create",
      "scooping-visit-unverification-detail",
      "scooping-visit-unverification-update",
      "scooping-visit-unverification-delete",
      "scooping-visit-unverification-lookup",
      "scooping-visit-unverification-list",
      "scooping-visit-gis-verification-create",
      "scooping-visit-gis-verification-detail",
      "scooping-visit-gis-verification-update",
      "scooping-visit-gis-verification-delete",
      "scooping-visit-gis-verification-lookup",
      "scooping-visit-gis-verification-list",
      "rra-pra-verification-create",
      "rra-pra-verification-detail",
      "rra-pra-verification-update",
      "rra-pra-verification-delete",
      "rra-pra-verification-lookup",
      "rra-pra-verification-list",
      "rra-pra-unverification-create",
      "rra-pra-unverification-detail",
      "rra-pra-unverification-update",
      "rra-pra-unverification-delete",
      "rra-pra-unverification-lookup",
      "rra-pra-unverification-list",
      "sosialisasi-program-verification-create",
      "sosialisasi-program-verification-detail",
      "sosialisasi-program-verification-update",
      "sosialisasi-program-verification-delete",
      "sosialisasi-program-verification-lookup",
      "sosialisasi-program-verification-list",
      "sosialisasi-program-unverification-create",
      "sosialisasi-program-unverification-detail",
      "sosialisasi-program-unverification-update",
      "sosialisasi-program-unverification-delete",
      "sosialisasi-program-unverification-lookup",
      "sosialisasi-program-unverification-list",
      "farmer-verification-create",
      "farmer-verification-detail",
      "farmer-verification-update",
      "farmer-verification-delete",
      "farmer-verification-lookup",
      "farmer-verification-list",
      "farmer-unverification-create",
      "farmer-unverification-detail",
      "farmer-unverification-update",
      "farmer-unverification-delete",
      "farmer-unverification-lookup",
      "farmer-unverification-list",
      "lahan-fc-verification-create",
      "lahan-fc-verification-detail",
      "lahan-fc-verification-update",
      "lahan-fc-verification-delete",
      "lahan-fc-verification-lookup",
      "lahan-fc-verification-list",
      "lahan-um-verification-create",
      "lahan-um-verification-detail",
      "lahan-um-verification-update",
      "lahan-um-verification-delete",
      "lahan-um-verification-lookup",
      "lahan-um-verification-list",
      "lahan-gis-verification-create",
      "lahan-gis-verification-detail",
      "lahan-gis-verification-update",
      "lahan-gis-verification-delete",
      "lahan-gis-verification-lookup",
      "lahan-gis-verification-list",
      "lahan-kml-bulk-upload-create",
      "lahan-kml-bulk-upload-detail",
      "lahan-kml-bulk-upload-update",
      "lahan-kml-bulk-upload-delete",
      "lahan-kml-bulk-upload-lookup",
      "lahan-kml-bulk-upload-list",
    ],
    maintenanceOverlay: false,
    packageVersion: version || "0",
    packageVersionDateTime: version_date_time || "0",
    theme: "light",
    programYear: {
      model: "2024",
      options: ["2020", "2021", "2022", "2023", "2024"],
    },
    taskForceTeam: {
      emails: TaskForceEmail,
    },
    maps: {
      accessToken:
        "pk.eyJ1IjoiYmlsbGlvbmFpcmUwMjkiLCJhIjoiY2p3a3V5Zms5MHdzaTN5bnhxenFvcHFiNiJ9.jrcibCk1tIIShgL_mh7ipA",
      mapStyle: "mapbox://styles/mapbox/satellite-streets-v12",
    },
    nurseryTeam: {
      emails: {
        Cirasea: Cirasea || [],
        Ciminyak: Ciminyak || [],
        Soreang: Soreang || [],
        Kebumen: Kebumen || [],
        Pati: Pati || [],
        JustLoadingLineModul: JustLoadingLineModul,
      },
    },
    User: localStorage.getItem("User")
      ? JSON.parse(localStorage.getItem("User"))
      : "",
  },
  getters: {
    getApiUrl: (state) => (url) => {
      return state.apiUrl + url;
    },
    getImageUrl: (state) => (url) => {
      return state.apiUrlImage + url;
    },
    capitalizeFirstLetter: () => (string) => {
      return string.charAt(0).toUpperCase() + string.slice(1);
    },
    ktpRules: (state) => (val) => {
      const ktpRegex = /^[0-9]{16}$/;
      const check = ktpRegex.test(val);
      return check;
    },
    numberFormat: () => (num) => {
      return new Intl.NumberFormat("id-ID", {
        maximumFractionDigits: 0,
      }).format(num);
    },
    dateFormat: () => (date, format) => {
      return moment(date).format(format);
    },
  },
  mutations: {
    set(state, [variable, value, saveLS = false]) {
      Vue.set(state, variable, value);
      if (saveLS)
        localStorage.setItem(
          variable,
          typeof value == "string" ? value : JSON.stringify(value)
        );
    },
  },
  actions: {},
  modules: {},
});
